# Nombre del flujo de trabajo que se mostrará en la pestaña "Actions" de GitHub.
name: CI/CD Pipeline

# Define los eventos que activarán la ejecución de este flujo de trabajo.
on:
  # Se activa cuando se hace un push a las ramas main o develop.
  push:
    branches:
      - main
      - develop
  # Se activa cuando se crea o actualiza un pull request dirigido a las ramas main o develop.
  pull_request:
    branches:
      - main
      - develop

# Define los trabajos (jobs) que se ejecutarán como parte del flujo de trabajo.
jobs:
  # Primer trabajo: "test". Su propósito es ejecutar las pruebas unitarias.
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python models/train_model.py

      - name: Run unit tests
        run: |
          pytest tests/ -v --cov=api --cov-report=term-missing

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()

  # Segundo trabajo: "build". Construye y sube la imagen de Docker.
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # -----------------------------------------------------------------
      # CORRECCIÓN DE ERROR (Instalar dependencias antes de re-entrenar)
      # -----------------------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Train model for Docker
        run: |
          python models/train_model.py
      # -----------------------------------------------------------------
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Inicia sesión en Docker Hub (SOLO en push a main para usar Secrets)
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construye y sube la imagen (SOLO en push a main)
      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/breast-cancer-api:latest
            ${{ secrets.DOCKER_USERNAME }}/breast-cancer-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Construye y prueba la imagen LOCALMENTE (en ramas develop o PR)
      - name: Build and Test Docker image (Local Only)
        if: github.ref != 'refs/heads/main'
        run: |
          docker build -t breast-cancer-api:latest .
          docker run -d -p 5000:5000 --name test-api breast-cancer-api:latest
          sleep 10
          curl -f http://localhost:5000/ || exit 1
          docker stop test-api
          docker rm test-api

  # Tercer trabajo: "integration-test". Ejecuta pruebas de integración contra el contenedor Docker.
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies (para ejecutar el script de test)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Entrenar el modelo (Necesario para construir la imagen localmente)
      - name: Train model
        run: |
          python models/train_model.py

      - name: Build Docker image for integration test
        run: |
          docker build -t breast-cancer-api:test .

      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name integration-test breast-cancer-api:test
          sleep 15

      # Usa el script de prueba de endpoints que ya tienes.
      - name: Run integration tests (API endpoints)
        run: |
          # Asumiendo que has movido el script de prueba a tests/test_endpoints.py y usa requests.
          python tests/test_endpoints.py 

      - name: Stop and remove container
        if: always()
        run: |
          docker stop integration-test || true
          docker rm integration-test || true